
load_run: model_weights/gnm_2025_04_10_00_52_20_hm3dBB3Sh4ES10_GTTM_ObNone_perturb0.3/

# KEY PARAMS
predict_dists: False
goal_type: "image_mask_enc" # ["image", "disabled", "image_mask_enc"]
obs_type: "disabled" # ["image", "disabled", "image_mask_enc"]
dims: 8
goal_uses_context: False
is_pl_normalized: False
use_vel_filter: True
use_mask_grad: False

# navigation params, from deployment/src/navigate.py
close_threshold: 3
loc_radius: 4
waypoint_index: -1
fixed_plan: False

# model params
model_type: gnm
obs_encoding_size: 1024
goal_encoding_size: 1024

# normalization for the action space
normalize: True

# context
context_type: temporal # [temporal, randomized]
context_size: 5

# action output params
len_traj_pred: 10
learn_angle: True

# dataset specific parameters
image_size: [85, 64] # width, height